# Generated by Django 5.2.7 on 2025-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("vendor", "vendor"), ("supplier", "supplier")], max_length=10
            ),
        ),
    ]
