# Generated by Django 5.2.7 on 2025-10-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_supplierprofile_address_supplierprofile_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="user",
        ),
    ]
