# Generated by Django 5.2.7 on 2025-10-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_supplierprofile_user_and_more"),
        ("products", "0003_alter_supplierproduct_supplier"),
        ("reviews", "0003_alter_productreview_supplier_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupplierProfile",
        ),
        migrations.DeleteModel(
            name="VendorProfile",
        ),
    ]
