# Generated by Django 5.2.7 on 2025-10-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order"),
        ("reviews", "0002_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews_received",
                to="orders.supplierprofile",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews_given",
                to="orders.vendorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to="orders.supplierprofile",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to="orders.vendorprofile",
            ),
        ),
    ]
