# Generated by Django 5.2.7 on 2025-10-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_notification"),
        ("reviews", "0003_alter_productreview_supplier_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="product_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(default="Review", max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("vendor", "supplier", "order")},
        ),
    ]
