# Generated by Django 5.2.7 on 2025-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_supplier_remove_order_supplier_remove_order_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="items",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
