# Generated by Django 5.2.7 on 2025-10-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_delivery_address_order_expected_delivery_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="expected_delivery_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
    ]
