# Generated by Django 5.2.7 on 2025-10-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_user_type"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="supplierproduct",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional description or notes about this product from the supplier",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["supplier", "is_available"],
                name="products_su_supplie_709ef6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["product", "is_available"],
                name="products_su_product_aa5cdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(fields=["price"], name="products_su_price_a65a5d_idx"),
        ),
    ]
