# Generated by Django 5.2.7 on 2025-10-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order"),
        ("products", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierproduct",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_products",
                to="orders.supplierprofile",
            ),
        ),
    ]
